(function (root) {
  const catalog = [
    { id: "A.1", category: "A. Contract Core", label: "schemaVersion fixed value ctp.card-transition.v1", testable: true },
    { id: "A.2", category: "A. Contract Core", label: "transitionId unique per transition", testable: true },
    { id: "A.3", category: "A. Contract Core", label: "transactionId groups related transitions", testable: true },
    { id: "A.4", category: "A. Contract Core", label: "seed for deterministic variation", testable: true },
    { id: "A.5", category: "A. Contract Core", label: "cardRef string form", testable: true },
    { id: "A.6", category: "A. Contract Core", label: "cardRef object form with instanceId", testable: true },
    { id: "A.7", category: "A. Contract Core", label: "action enum coverage", testable: true },

    { id: "B.1", category: "B. Zones and Coordinates", label: "from.zoneId abstract source zone", testable: true },
    { id: "B.2", category: "B. Zones and Coordinates", label: "to.zoneId abstract target zone", testable: true },
    { id: "B.3", category: "B. Zones and Coordinates", label: "seatId context on from/to", testable: true },
    { id: "B.4", category: "B. Zones and Coordinates", label: "slotId context on from/to", testable: true },
    { id: "B.5", category: "B. Zones and Coordinates", label: "anchor presets", testable: true },
    { id: "B.6", category: "B. Zones and Coordinates", label: "custom anchor with anchorVector", testable: true },
    { id: "B.7", category: "B. Zones and Coordinates", label: "offsetPx local anchor offset", testable: true },
    { id: "B.8", category: "B. Zones and Coordinates", label: "coordinateSpace variants", testable: true },

    { id: "C.1", category: "C. Motion and Timing", label: "timing.durationMs canonical duration", testable: true },
    { id: "C.2", category: "C. Motion and Timing", label: "timing.delayMs", testable: true },
    { id: "C.3", category: "C. Motion and Timing", label: "timing.easing", testable: true },
    { id: "C.4", category: "C. Motion and Timing", label: "timing.speedProfile", testable: true },
    { id: "C.5", category: "C. Motion and Timing", label: "timing.normalizeByDistance", testable: true },
    { id: "C.6", category: "C. Motion and Timing", label: "timing.minDurationMs", testable: true },
    { id: "C.7", category: "C. Motion and Timing", label: "timing.maxDurationMs", testable: true },
    { id: "C.8", category: "C. Motion and Timing", label: "timing.phases list", testable: true },
    { id: "C.9", category: "C. Motion and Timing", label: "path.linear", testable: true },
    { id: "C.10", category: "C. Motion and Timing", label: "path.arc", testable: true },
    { id: "C.11", category: "C. Motion and Timing", label: "path.bezier", testable: true },
    { id: "C.12", category: "C. Motion and Timing", label: "path.spline", testable: false },
    { id: "C.13", category: "C. Motion and Timing", label: "path.teleport", testable: true },
    { id: "C.14", category: "C. Motion and Timing", label: "path.custom", testable: false },
    { id: "C.15", category: "C. Motion and Timing", label: "path.controlPoints", testable: true },
    { id: "C.16", category: "C. Motion and Timing", label: "path.arcHeightPx", testable: true },
    { id: "C.17", category: "C. Motion and Timing", label: "path.jitterPx", testable: false },
    { id: "C.18", category: "C. Motion and Timing", label: "orientation.startTiltDeg", testable: true },
    { id: "C.19", category: "C. Motion and Timing", label: "orientation.endTiltDeg", testable: true },
    { id: "C.20", category: "C. Motion and Timing", label: "orientation.startRotateDeg", testable: true },
    { id: "C.21", category: "C. Motion and Timing", label: "orientation.endRotateDeg", testable: true },
    { id: "C.22", category: "C. Motion and Timing", label: "orientation.spinTurns", testable: false },

    { id: "D.1", category: "D. Visibility and Audience", label: "visibility mode face_up_always", testable: true },
    { id: "D.2", category: "D. Visibility and Audience", label: "visibility mode face_down_always", testable: true },
    { id: "D.3", category: "D. Visibility and Audience", label: "visibility mode face_down_until_arrival", testable: true },
    { id: "D.4", category: "D. Visibility and Audience", label: "visibility mode flip_on_start", testable: true },
    { id: "D.5", category: "D. Visibility and Audience", label: "visibility mode flip_on_complete", testable: true },
    { id: "D.6", category: "D. Visibility and Audience", label: "visibility mode flip_at_progress", testable: true },
    { id: "D.7", category: "D. Visibility and Audience", label: "visibility mode flip_at_phase", testable: false },
    { id: "D.8", category: "D. Visibility and Audience", label: "visibility startFace/endFace", testable: true },
    { id: "D.9", category: "D. Visibility and Audience", label: "visibility perAudience face states", testable: true },
    { id: "D.10", category: "D. Visibility and Audience", label: "audience.visibility public/owner/hidden/custom", testable: false },
    { id: "D.11", category: "D. Visibility and Audience", label: "audience.ownerId", testable: false },
    { id: "D.12", category: "D. Visibility and Audience", label: "audience includeIds/excludeIds", testable: false },
    { id: "D.13", category: "D. Visibility and Audience", label: "visibility flipAnimation.durationMs", testable: true },
    { id: "D.14", category: "D. Visibility and Audience", label: "visibility flipAnimation.easing", testable: true },
    { id: "D.15", category: "D. Visibility and Audience", label: "visibility flipAnimation.axis", testable: true },
    { id: "D.16", category: "D. Visibility and Audience", label: "visibility flipAnimation.revealAtProgress", testable: true },

    { id: "E.1", category: "E. Commit and Insert", label: "stateCommitPolicy on_start", testable: true },
    { id: "E.2", category: "E. Commit and Insert", label: "stateCommitPolicy on_progress", testable: true },
    { id: "E.3", category: "E. Commit and Insert", label: "stateCommitPolicy on_phase", testable: false },
    { id: "E.4", category: "E. Commit and Insert", label: "stateCommitPolicy on_complete", testable: true },
    { id: "E.5", category: "E. Commit and Insert", label: "stateCommitPolicy external", testable: false },
    { id: "E.6", category: "E. Commit and Insert", label: "stateCommitPolicy waitForAck", testable: false },
    { id: "E.7", category: "E. Commit and Insert", label: "insertPolicy none", testable: true },
    { id: "E.8", category: "E. Commit and Insert", label: "insertPolicy ghost_until_commit", testable: true },
    { id: "E.9", category: "E. Commit and Insert", label: "insertPolicy insert_on_start", testable: false },
    { id: "E.10", category: "E. Commit and Insert", label: "insertPolicy insert_on_progress", testable: false },
    { id: "E.11", category: "E. Commit and Insert", label: "insertPolicy insert_on_complete", testable: false },
    { id: "E.12", category: "E. Commit and Insert", label: "insertPolicy containerZoneId", testable: true },
    { id: "E.13", category: "E. Commit and Insert", label: "insertPolicy indexStrategy", testable: false },
    { id: "E.14", category: "E. Commit and Insert", label: "insertPolicy absoluteIndex guard", testable: false },
    { id: "E.15", category: "E. Commit and Insert", label: "insertPolicy relativeCardId guard", testable: false },

    { id: "F.1", category: "F. Concurrency and Sequence", label: "sequence.orderIndex", testable: true },
    { id: "F.2", category: "F. Concurrency and Sequence", label: "sequence.staggerMs", testable: true },
    { id: "F.3", category: "F. Concurrency and Sequence", label: "sequence.batchSize", testable: true },
    { id: "F.4", category: "F. Concurrency and Sequence", label: "sequence.waveIndex", testable: true },
    { id: "F.5", category: "F. Concurrency and Sequence", label: "concurrency.groupId", testable: true },
    { id: "F.6", category: "F. Concurrency and Sequence", label: "concurrency.mode independent", testable: true },
    { id: "F.7", category: "F. Concurrency and Sequence", label: "concurrency.mode simultaneous", testable: true },
    { id: "F.8", category: "F. Concurrency and Sequence", label: "concurrency.mode staggered", testable: true },
    { id: "F.9", category: "F. Concurrency and Sequence", label: "concurrency.mode sequential", testable: true },
    { id: "F.10", category: "F. Concurrency and Sequence", label: "concurrency.mode wave", testable: true },
    { id: "F.11", category: "F. Concurrency and Sequence", label: "concurrency.maxParallel", testable: false },
    { id: "F.12", category: "F. Concurrency and Sequence", label: "concurrency.barrierBefore", testable: false },
    { id: "F.13", category: "F. Concurrency and Sequence", label: "concurrency.barrierAfter", testable: false },
    { id: "F.14", category: "F. Concurrency and Sequence", label: "deal 4 at once to one player", testable: true },
    { id: "F.15", category: "F. Concurrency and Sequence", label: "sequence.packetId for deal blocks", testable: true },
    { id: "F.16", category: "F. Concurrency and Sequence", label: "sequence.packetSlotIndex", testable: true },
    { id: "F.17", category: "F. Concurrency and Sequence", label: "sequence.holdFormationUntilProgress", testable: true },
    { id: "F.18", category: "F. Concurrency and Sequence", label: "sequence.formationCompactness", testable: true },
    { id: "F.19", category: "F. Concurrency and Sequence", label: "arbitrary block-size dealing driven by game logic", testable: true },

    { id: "G.1", category: "G. Interrupt and Recovery", label: "interruptPolicy cancel", testable: true },
    { id: "G.2", category: "G. Interrupt and Recovery", label: "interruptPolicy complete_fast", testable: true },
    { id: "G.3", category: "G. Interrupt and Recovery", label: "interruptPolicy snap_to_end", testable: true },
    { id: "G.4", category: "G. Interrupt and Recovery", label: "interruptPolicy ignore", testable: false },
    { id: "G.5", category: "G. Interrupt and Recovery", label: "reconcile after reconnect", testable: true },
    { id: "G.6", category: "G. Interrupt and Recovery", label: "no reveal before authoritative gate", testable: true },

    { id: "H.1", category: "H. Accessibility and Invariants", label: "respectReducedMotion", testable: true },
    { id: "H.2", category: "H. Accessibility and Invariants", label: "reducedMotionMode none", testable: true },
    { id: "H.3", category: "H. Accessibility and Invariants", label: "reducedMotionMode shorten", testable: true },
    { id: "H.4", category: "H. Accessibility and Invariants", label: "reducedMotionMode fade", testable: true },
    { id: "H.5", category: "H. Accessibility and Invariants", label: "reducedMotionMode snap", testable: true },
    { id: "H.6", category: "H. Accessibility and Invariants", label: "reducedDurationMs", testable: true },
    { id: "H.7", category: "H. Accessibility and Invariants", label: "maxDurationMs", testable: false },
    { id: "H.8", category: "H. Accessibility and Invariants", label: "preserveAuthoritativeEvents", testable: true },
    { id: "H.9", category: "H. Accessibility and Invariants", label: "authoritative flip/reveal/commit invariant", testable: true },

    { id: "I.1", category: "I. Events and Hooks", label: "events emit on_start", testable: true },
    { id: "I.2", category: "I. Events and Hooks", label: "events emit on_phase_start", testable: false },
    { id: "I.3", category: "I. Events and Hooks", label: "events emit on_flip", testable: true },
    { id: "I.4", category: "I. Events and Hooks", label: "events emit on_commit", testable: true },
    { id: "I.5", category: "I. Events and Hooks", label: "events emit on_complete", testable: true },
    { id: "I.6", category: "I. Events and Hooks", label: "events emit on_interrupt", testable: true },
    { id: "I.7", category: "I. Events and Hooks", label: "events.channel", testable: false },

    { id: "J.1", category: "J. Extensibility", label: "metadata extension bag", testable: true },
    { id: "J.2", category: "J. Extensibility", label: "xExtensions extension bag", testable: true },

    { id: "K.1", category: "K. Renderer Boundary", label: "clipping kept out of CardTransition", testable: true },
    { id: "K.2", category: "K. Renderer Boundary", label: "ZoneRenderProfile separate contract", testable: true },
    { id: "K.3", category: "K. Renderer Boundary", label: "ZoneRenderProfile layers", testable: true },
    { id: "K.4", category: "K. Renderer Boundary", label: "ZoneRenderProfile clipMode variants", testable: true },
    { id: "K.5", category: "K. Renderer Boundary", label: "ZoneRenderProfile overflowBehavior variants", testable: true },
    { id: "K.6", category: "K. Renderer Boundary", label: "ZoneRenderProfile geometry hints", testable: true },

    { id: "L.1", category: "L. Potential Extensions", label: "per-audience flip timing", testable: false, status: "future" },
    { id: "L.2", category: "L. Potential Extensions", label: "packInstanceId identity convention", testable: false, status: "future" },
    { id: "L.3", category: "L. Potential Extensions", label: "transaction envelope schema", testable: false, status: "future" }
  ];

  if (typeof module !== "undefined" && module.exports) {
    module.exports = catalog;
  }

  root.TRANSITION_FEATURE_CATALOG = catalog;
})(typeof globalThis !== "undefined" ? globalThis : this);
